env:
  global:
cache:
    directories:
      - $HOME/build_cache


sudo: required
dist: trusty
osx_image: xcode6.4

install_linux: &install_linux
  - test 1 = 1


install_osx: &install_osx
  - test 1 = 1


matrix:
  include:
    # test linux
    - stage: test
      os: linux
      env:
        - IS_LINUX=1
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "script linux 2"

    - stage: test
      os: linux
      env:
        - IS_LINUX=1
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "script linux 2"

    # test osx
    - stage: test
      os: osx
      env:
        - IS_OSX=1
      install: *install_osx
      script:
        - echo "script osx 1"

    - stage: test
      os: osx
      env:
        - IS_OSX=1
      install: *install_osx
      script:
        - echo "script osc 2"

    # deploy linux
    - stage: deploy
      os: linux
      script:
        - echo "deploy linux"

    # deploy osx
    - stage: deploy
      os: osx
      script:
        - echo "deploy osx"

