env:
  global:
cache:
    directories:
      - $HOME/build_cache


sudo: required
dist: trusty
osx_image: xcode6.4

install_linux: &install_linux
  - test 1 = 1


install_osx: &install_osx
  - test 1 = 1


do_cache: &do_cache
  if [ -d "$HOME/build_cache/foo" ]; then
    echo "build cache available";
  fi

do_create: &do_create
  if [ ! -d "$HOME/build_cache/foo" ]; then
    mkdir $HOME/build_cache/foo;
  fi

matrix:
  include:
    # test linux
    - stage: cache
      os: linux
      env:
        - IS_LINUX=1
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "cache linux"
        - *do_cache
        - *do_create

    - stage: test
      os: linux
      env:
        - IS_LINUX=2
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "script linux"
        - *do_cache

    # test osx
    - stage: cache
      os: osx
      env:
        - IS_OSX=1
      install: *install_osx
      script:
        - echo "cache osx"
        - *do_cache
        - *do_create

    - stage: test
      os: osx
      env:
        - IS_OSX=2
      install: *install_osx
      script:
        - echo "script osx"
        - *do_cache


    # deploy linux
    - stage: deploy
      os: linux
      script:
        - echo "deploy linux"
        - *do_cache

    # deploy osx
    - stage: deploy
      os: osx
      script:
        - echo "deploy osx"
        - *do_cache

