env:
  global:
cache:
    directories:
      - $HOME/build_cache


sudo: required
dist: trusty
osx_image: xcode6.4

install_linux: &install_linux
  - test 1 = 1


install_osx: &install_osx
  - test 1 = 1


do_cache: &do_cache
  if [ -d "$HOME/build_cache" ]; then
    echo "build cache available";
  fi

matrix:
  include:
    # test linux
    - stage: test
      os: linux
      env:
        - IS_LINUX=1
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "script linux 1"
        - *do_cache

    - stage: test
      os: linux
      env:
        - IS_LINUX=1
      before_install:
        - echo "before"
      install: *install_linux
      script:
        - echo "script linux 2"
        - *do_cache

    # test osx
    - stage: test
      os: osx
      env:
        - IS_OSX=1
      install: *install_osx
      script:
        - echo "script osx 1"
        - *do_cache

    - stage: test
      os: osx
      env:
        - IS_OSX=1
      install: *install_osx
      script:
        - echo "script osx 2"
        - *do_cache

    # deploy linux
    - stage: deploy
      os: linux
      script:
        - echo "deploy linux"

    # deploy osx
    - stage: deploy
      os: osx
      script:
        - echo "deploy osx"

