env:
  global:
cache:
    apt: true

sudo: required
dist: trusty
osx_image: xcode6.4
addons: &addons

install_linux: &install_linux
  # Install dependencies
  - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin system
  - export OPAMYES=1
  - opam install sedlex xml-light extlib rope ptmap
  # Install neko
  - git clone https://github.com/HaxeFoundation/neko.git ../neko
  - pushd ../neko
  - cmake . -DSTATIC_DEPS=all
  # download static dependencies before actual build, with 3 chances to deal with network issues
  - make download_static_deps || make download_static_deps || make download_static_deps
  - make
  - sudo make install
  - popd
  # Setup database
  - travis_retry sudo apt-get install mysql-server-5.6 -y
  - mysql -u root -e "create user travis@localhost identified by '';"
  - mysql -u root -e "create database haxe_test;"
  - mysql -u root -e "grant all on haxe_test.* to travis@localhost;"
  # Setup JDK
  - jdk_switcher use oraclejdk7
  - java -version


install_osx: &install_osx
  # Install dependencies
  - brew uninstall --force brew-cask # https://github.com/caskroom/homebrew-cask/pull/15381
  - travis_retry brew update
  - travis_retry brew install opam;
  - export OPAMYES=1
  - opam init
  - opam install camlp4 sedlex ocamlfind xml-light extlib rope ptmap
  - eval `opam config env`
  # Install neko
  - brew upgrade cmake # we need a recent cmake to use CMAKE_OSX_DEPLOYMENT_TARGET
  - git clone https://github.com/HaxeFoundation/neko.git ../neko
  - pushd ../neko
  - cmake . -DSTATIC_DEPS=all
  # download static dependencies before actual build, with 3 chances to deal with network issues
  - make download_static_deps || make download_static_deps || make download_static_deps
  - make
  - sudo make install
  - popd
  # Setup database
  - travis_retry brew install mysql
  - mysql.server start
  - mysql -u root -e "create user if not exists travis@localhost identified by '';"
  - mysql -u root -e "create database haxe_test;"
  - mysql -u root -e "grant all on haxe_test.* to travis@localhost;"


matrix:
  include:
    #########
    # linux #
    #########
    - os: linux
      env:
        - TEST=macro,neko,js,php,php7,flash9,as3,java,cs,python,hl,lua
        - DEPLOY=1
        # - SAUCE=1
      # addons:
      #   <<: *addons
      #  sauce_connect: true
      before_install:
        - sudo apt-get update -y || true
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "export AUDIODEV=null"
        - sudo add-apt-repository ppa:haxe/ocaml -y
        - sudo apt-get update
        - sudo apt-get install -y
            ocaml
            ocaml-native-compilers
            ocaml-findlib
            camlp4
            libpcre3-dev
            zlib1g-dev
            libgtk2.0-dev
            awscli
      install: *install_linux

    - os: linux
      env:
        - TEST=cpp
        - HXCPP_COMPILE_CACHE=~/hxcache
      before_install:
        - sudo apt-get update -y || true
        - travis_retry sudo apt-get install -y
            gcc-multilib
            g++-multilib
        - sudo add-apt-repository ppa:haxe/ocaml -y
        - sudo apt-get update
        - sudo apt-get install -y
            ocaml
            ocaml-native-compilers
            ocaml-findlib
            camlp4
            libpcre3-dev
            zlib1g-dev
            libgtk2.0-dev
            awscli
      install: *install_linux

    #######
    # osx #
    #######
    - os: osx
      env:
        - TEST=macro,neko,js,php,flash9,as3,java,cs,python,hl,lua
        - DEPLOY=1
      install: *install_osx

    - os: osx
      env:
        - TEST=cpp
        - HXCPP_COMPILE_CACHE=~/hxcache
      install: *install_osx

branches:
  except:
    # A hack to prevent building for tags, assuming they all start with a number.
    # https://github.com/travis-ci/travis-ci/issues/1532
    - /^[0-9]/
